config/routes.rb
UserService::Application.routes.draw do
  scope "(:locale)", :locale => /#{I18n.available_locales.join('|')}/ do
    mount Doorkeeper::Engine => '/oauth'
    mount SudoMode::Engine => '/sudo'

    get 'register', :to => 'organizations#new', :as => 'register'
    get 'login', :to => 'sessions#new', :as => 'login'
    get 'logout', :to => 'sessions#destroy', :as => 'logout'

    get 'deactivated_organization', :to => 'static_pages#deactivated_organization', :as => 'deactivated'

    resources :sessions
    resources :password_resets
    resources :organizations do
      resources :users, :except => [:destroy]
      put 'activate', 'deactivate'
    end

    resources :documents, :only => [:new, :create, :index]

    root :to => 'sessions#new'
  end

  namespace :api, :defaults => { :format => 'json' } do
    scope :module => :v1 do
      get 'me', :to => "users#me"
      get 'users/users_for_ids', :to => "users#users_for_ids"
      get 'users/validate_users', :to => "users#validate_users"
      get 'organizations/validate_orgs', :to => "organizations#validate_orgs"
      resources :organizations, :shallow => true, :only => [:index, :show] do
        resources :users, :shallow => true, :only => [:index]
      end
      resources :deleted_organizations, :shallow => true, :only => :index
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include SoftDeletable

  attr_accessible :email, :name, :password, :password_confirmation, :role, :status
  has_secure_password
  validates_presence_of :email, :name
  validates_presence_of :password, :password_confirmation, :on => :create
  validates_email_format_of :email
  validate :role_is_valid
  validates_uniqueness_of :email,:case_sensitive => false
  belongs_to :organization
  before_validation :default_values
  before_save :convert_email_to_lower_case
  delegate :active?, :to => :organization, :prefix => true

  scope :super_admins, where(:role => "super_admin")
  scope :cso_admins, where(:role => "cso_admin")
  scope :super_admins_and_cso_admins_for, -> organization_id { where("(role = ?) OR (role = ? AND organization_id = ?)",
                                                                     "super_admin", "cso_admin", organization_id) }

  ROLES = %w(viewer field_agent supervisor designer manager cso_admin super_admin)

  module Status
    ACTIVE = "active"
    PENDING = "pending"
    INACTIVE = "inactive"
  end

  scope :active_users,   where(:status => Status::ACTIVE)
  scope :pending_users,  where(:status => Status::PENDING)
  scope :inactive_users, where(:status => Status::INACTIVE)

  def self.maybe(user)
    user || NullUser.new
  end

  ROLES.each do |role|
    define_method((role + "?").to_sym) do
      self.role == role
    end
  end

  def active?
    status == Status::ACTIVE
  end

  def inactive?
    status == Status::INACTIVE
  end

  def send_password_reset
    generate_password_reset_token
    UserMailer.delay(:queue => "password_reset_mail").password_reset_mail(self)
  end

  def generate_password_reset_token
   begin
    self[:password_reset_token] = SecureRandom.urlsafe_base64
   end while User.exists?(:password_reset_token => self[:password_reset_token])
   save!
  end

  def reset_password(password, password_confirmation)
    return false if password.blank?
    self.password = password
    self.password_confirmation = password_confirmation
    self.password_reset_token = nil
    self.status = Status::ACTIVE
    save
  end

  def generate_password
    token = SecureRandom.urlsafe_base64
    self.password = token
    self.password_confirmation = token
  end

  def self.valid_ids?(user_ids)
    user_ids.all? { |user_id| exists?(user_id) }
  end

  def available_roles
    if role == "super_admin"
      ROLES
    else
      ROLES.reject { |role| role == 'super_admin' }
    end
  end

  private

  def convert_email_to_lower_case
    self.email = self.email.downcase
  end

  def role_is_valid
    errors.add(:role, "Invalid role specified") unless ROLES.include? role
  end

  def default_values
    self.role ||= "field_agent"
    self.status ||= User::Status::PENDING
  end
end

class NullUser
  %w(super_admin? active? organization_active?).each do |method|
    define_method(method.to_sym) do
      true
    end
  end

  def authenticate(*args)
    false
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ActionController::Base
      doorkeeper_for :all
      load_and_authorize_resource :user, :parent => false, :except => [:validate_users, :index]
      respond_to :json

      def me
        respond_with current_user.to_json(:except => :password_digest,
                                          :include => { :organization => { :only => [:org_type, :name] }})
      end

      def index
        organization = Organization.find_by_id(params[:organization_id])
        authorize! :read, organization
        users = organization.users.active_users
        user_ids = params[:user_ids]
        users = users.where(:id => user_ids) if user_ids
        respond_with users.to_json(:only => [:id, :name, :role, :email])
      end

      def users_for_ids
        user_ids = JSON.parse params[:user_ids]
        users = User.where(:id => user_ids) if user_ids
        respond_with users.to_json(:only => [:id, :name, :email, :role])
      end

     def validate_users
       authorize! :read, User
       user_ids = JSON.parse(params[:user_ids])
       respond_with User.valid_ids?(user_ids).to_json
     end

      private

      def current_user
        @current_user ||= User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def new
    @user = User.new
  end

  def index
    organization = Organization.find(params[:organization_id])
    @users = organization.users
  end

  def create
    organization = Organization.find(params[:organization_id])
    @user = organization.users.new(params[:user])
    @user.generate_password
    if @user.save
      flash[:notice] = t "users.create.user_created_successfully"
      @user.send_password_reset
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
    @organization = @user.organization
  end

  def update
    @user = User.find_by_id(params[:id])
    @organization = @user.organization
    if @user.update_attributes(params[:user])
      flash[:notice] = t "users.update.user_updated"
      redirect_to organization_users_path, :organization_id => @user.organization_id
    else
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end
end

app/views/users/_users_list.html.erb
<div id="user_list">
  <% unless users.empty? %>
    <header>
      <h2><%= t ".list_of_users" %></h2>
    </header>

    <% if users.pending_users.count > 0 %>
      <div>
      <h2><%= t ".pending" %></h2>
      <table>
        <% users.where("status = 'pending'").each do |user|%>
          <tr>
            <td><%= user.name %></td>
            <td><%= mail_to user.email %></td>
            <td><%= link_to :edit, edit_organization_user_path(user.organization_id, user.id) %></td>
          </tr>
        <% end %>
      </table>
    </div>
    <% end %>

    <% if users.inactive_users.count > 0 %>
      <div>
        <h2><%= t ".inactive" %></h2>
        <table>
          <% users.inactive_users.each do |user|%>
            <tr>
              <td><%= user.name %></td>
              <td><%= mail_to user.email %></td>

              <td><%= link_to :activate, organization_user_path(user.organization_id, user.id, :user => { :status => User::Status::ACTIVE }), :method => 'PUT' %></td>
              <td><%= link_to :edit, edit_organization_user_path(user.organization_id, user.id) %></td>
            </tr>
          <% end %>
        </table>
      </div>
    <% end %>

    <% if users.active_users.count > 0 %>
      <div>
      <h2><%= t ".active" %></h2>
      <table>
          <% users.active_users.each do |user|%>
            <tr>
              <td> <%= user.name %> </td>
              <td> <%= mail_to user.email %> </td>

              <td>
                <% unless user == current_user %>
                  <%= link_to :deactivate, organization_user_path(user.organization_id, user.id, :user => { :status => User::Status::INACTIVE }), :method => 'PUT' %>
                <% end %>
              </td>
              <td><%= link_to :edit, edit_organization_user_path(user.organization_id, user.id) %></td>
            </tr>
          <% end %>
      </table>
    </div>
    <% end %>
  <% else %>
    <p><%= t(".no_users") %></p>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= semantic_form_for @user, :url => organization_user_path(@organization.id, @user.id) do |f| %>
    <%= f.inputs do %>
        <%= f.input :name %>
        <%=  f.label :role %>
        <%= f.collection_select :role, current_user.available_roles, :to_s, :humanize %>
    <% end %>

    <%= f.actions do %>
        <% f.action :submit, :label => t(".update_button"), :as => :button %>
    <% end %>
<% end %>

app/views/users/index.html.erb
<%= render "users_list", :users => @users %>

app/views/users/new.html.erb
<div id="register">
  <header>
    <h2><%= "Register User" %></h2>
  </header>

  <%= semantic_form_for @user, :url => organization_users_path do |f| %>
    <%= f.inputs do %>
      <%= f.input :name %>
      <%= f.input :email %>
      <%= f.collection_select :role, current_user.available_roles, :to_s, :humanize %>
    <% end %>

    <%= f.actions do %>
      <% f.action :submit, :label => t("register"), :as => :button %>
    <% end %>
  <% end %>
</div>