config/routes.rb
UserService::Application.routes.draw do
  scope "(:locale)", :locale => /#{I18n.available_locales.join('|')}/ do
    mount Doorkeeper::Engine => '/oauth'
    mount SudoMode::Engine => '/sudo'

    get 'register', :to => 'organizations#new', :as => 'register'
    get 'login', :to => 'sessions#new', :as => 'login'
    get 'logout', :to => 'sessions#destroy', :as => 'logout'

    get 'deactivated_organization', :to => 'static_pages#deactivated_organization', :as => 'deactivated'

    resources :sessions
    resources :password_resets
    resources :organizations do
      resources :users, :except => [:destroy]
      put 'activate', 'deactivate'
    end

    resources :documents, :only => [:new, :create, :index]

    root :to => 'sessions#new'
  end

  namespace :api, :defaults => { :format => 'json' } do
    scope :module => :v1 do
      get 'me', :to => "users#me"
      get 'users/users_for_ids', :to => "users#users_for_ids"
      get 'users/validate_users', :to => "users#validate_users"
      get 'organizations/validate_orgs', :to => "organizations#validate_orgs"
      resources :organizations, :shallow => true, :only => [:index, :show] do
        resources :users, :shallow => true, :only => [:index]
      end
      resources :deleted_organizations, :shallow => true, :only => :index
    end
  end
end

app/models/document.rb
require 'active_support/concern'

module Document
  extend ActiveSupport::Concern

  included do
    validates :document, :presence => true
    attr_accessible :document
    mount_uploader :document, DocumentUploader
  end

  module ClassMethods
    def latest
      order("created_at DESC").first
    end
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  authorize_resource :class => false

  def new
    @terms_of_service = TermsOfService.new
    @privacy_policy = PrivacyPolicy.new
  end


  def create
    documents = DocumentPresenter.new(params[:documents])

    if documents.save
      flash[:notice] = t('documents.create.document_uploaded')
      redirect_to documents_path
    else
      flash[:error] = [t('documents.create.failed_upload')] + documents.errors.full_messages.flatten
      render :new
    end
  end

  def index
    @terms_of_service = TermsOfService.latest
    @privacy_policy = PrivacyPolicy.latest
  end
end

app/views/documents/index.html.erb
<div class="documents">
  <header>
    <%= link_to t(".upload_documents_button"), new_document_path %>
    <h2><%= t(".documents_title") %></h2>
  </header>

  <div class="display-document">
    <h2 class="title"><%= t(".terms_of_service_title") %></h2>
    <% if @terms_of_service.present? %>
      <iframe src="<%= @terms_of_service.document_url %>"></iframe>
    <% else %>
      <p><%= t(".terms_of_service_not_uploaded_message") %></p>
    <% end %>
  </div>

  <div class="display-document">
    <h2 class="title"><%= t(".privacy_policy_title") %></h2>
    <% if @privacy_policy.present? %>
      <iframe src="<%= @privacy_policy.document_url %>"></iframe>
    <% else %>
      <p><%= t(".privacy_policy_not_uploaded_message") %></p>
    <% end %>
  </div>
</div>

app/views/documents/new.html.erb
<div class="documents">
  <header>
    <h2><%= t(".upload_documents_title") %></h2>
  </header>


  <%= form_for(:documents, :url => documents_path, :html => { :class => "upload-form", :multipart => true }) do |f| %>
    <div class="form-section">
      <h2><%= t(".terms_of_service_title") %></h2>
      <%= f.fields_for @terms_of_service do |tos_form| %>
        <%= tos_form.label t('.upload_terms_of_service_message') %>
        <%= tos_form.file_field :document, :class => 'upload-field', :accept => "application/pdf" %>
      <% end %>
    </div>

    <div class="form-section">
      <h2><%= t(".privacy_policy_title") %></h2>
      <%= f.fields_for @privacy_policy do |privacy_policy_form| %>
        <%= privacy_policy_form.label t(".upload_privacy_policy_message") %>
        <%= privacy_policy_form.file_field :document, :class => 'upload-field', :accept => "application/pdf" %>
      <% end %>
    </div>

    <p class="upload-error">
      <%= t('.no_files_added_message') %>
    </p>
    <%= f.submit t(".upload_button_text"), :class => 'upload-action' %>
  <% end %>

  <script type="text/javascript">
    $(document).ready(function() {
      new UserOwner.DocumentUploader($(".upload-form"))
    });
  </script>
</div>