config/routes.rb
UserService::Application.routes.draw do
  scope "(:locale)", :locale => /#{I18n.available_locales.join('|')}/ do
    mount Doorkeeper::Engine => '/oauth'
    mount SudoMode::Engine => '/sudo'

    get 'register', :to => 'organizations#new', :as => 'register'
    get 'login', :to => 'sessions#new', :as => 'login'
    get 'logout', :to => 'sessions#destroy', :as => 'logout'

    get 'deactivated_organization', :to => 'static_pages#deactivated_organization', :as => 'deactivated'

    resources :sessions
    resources :password_resets
    resources :organizations do
      resources :users, :except => [:destroy]
      put 'activate', 'deactivate'
    end

    resources :documents, :only => [:new, :create, :index]

    root :to => 'sessions#new'
  end

  namespace :api, :defaults => { :format => 'json' } do
    scope :module => :v1 do
      get 'me', :to => "users#me"
      get 'users/users_for_ids', :to => "users#users_for_ids"
      get 'users/validate_users', :to => "users#validate_users"
      get 'organizations/validate_orgs', :to => "organizations#validate_orgs"
      resources :organizations, :shallow => true, :only => [:index, :show] do
        resources :users, :shallow => true, :only => [:index]
      end
      resources :deleted_organizations, :shallow => true, :only => :index
    end
  end
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  include SoftDeletable

  attr_accessible :name, :logo
  has_many :users
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_inclusion_of :default_locale, :in => I18n.available_locales.map(&:to_s)
  validates_inclusion_of :org_type, :in => proc { Organization.types }

  mount_uploader :logo, LogoUploader

  after_create :notify_super_admins_if_organization_allows_sharing

  def active?
    status == Organization::Status::ACTIVE
  end

  def activate
    self.status = Status::ACTIVE
    self.save
  end

  def deactivate
    self.status = Status::INACTIVE
    self.save
  end

  def field_agents
    users.where(:role => 'field_agent')
  end

  def cso_admins
    users.where(:role => 'cso_admin')
  end

  def self.types
    organization = YAML.load_file("#{Rails.root}/config/organization_types.yml")
    organization["types"].split(',').map(&:strip)
  end

  def self.build(org_params, cso_admin_params)
    organization = Organization.new(:name => org_params[:name])
    organization.logo = org_params[:logo]
    organization.org_type = org_params[:org_type]
    organization.allow_sharing = org_params[:allow_sharing]
    cso_admin = User.new(cso_admin_params)
    cso_admin.role = "cso_admin"
    cso_admin.status = User::Status::ACTIVE
    organization.users <<  cso_admin
    organization
  end

  def self.active_organizations
    where(:status => Status::ACTIVE)
  end

  def self.valid_ids?(org_ids)
    org_ids.all? { |org_id| exists?(org_id) }
  end

  module Status
    ACTIVE   = "active"
    INACTIVE = "inactive"
  end

  def soft_delete_self_and_associated
    OrganizationMailer.delay(:queue => "deregister_organization_notify_superadmins").
        notify_deregister_organization_for(User.super_admins_and_cso_admins_for(self.id).pluck("email"), self.name)
    users.each(&:soft_delete)
    self.delay(:queue => "deregister_organization", :run_at => 48.hours.from_now).soft_delete
  end

  private

  def notify_super_admins_if_organization_allows_sharing
    OrganizationMailer.delay(:queue => "allow_sharing_email").notify_super_admins_of_organization_that_allows_sharing(self.name) if self.allow_sharing?
  end
end

app/controllers/api/v1/organizations_controller.rb
module Api
  module V1
    class OrganizationsController < ActionController::Base
      skip_authorize_resource
      doorkeeper_for :all
      respond_to :json

      def index
        organizations = Organization.active_organizations
        respond_with organizations.to_json(:only => [:id, :name])
      end

      def validate_orgs
        org_ids = JSON.parse(params[:org_ids])
        respond_with Organization.valid_ids?(org_ids).to_json
      end

      def show
        organization = Organization.find_by_id(params[:id])
        if(organization)
          render :json => organization.decorate.to_json
        else
          render :nothing => true, :status => :bad_request
        end
      end
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  load_and_authorize_resource :except => :create
  require_password_confirmation_for :destroy

  def new
    @organization = Organization.new.decorate
    @user = @organization.users.new
  end

  def create
    @organization = Organization.build(params[:organization],
                                       params[:organization][:users])

    @organization.default_locale = I18n.locale.to_s

    if @organization.save
      redirect_to root_path
      flash[:notice] = t("successful_create_message")
    else
      @organization = @organization.decorate
      @user = @organization.users.first
      flash[:error] = t("creation_failed")
      render :new
    end
  end

  def edit
    @organization = Organization.find(params[:id])
  end

  def update
    organization = Organization.find(params[:id])
    organization.update_attributes(params[:organization])
    flash[:notice] = t("organizations.update.successful_organization_edit_flash_notice")
    redirect_to organization_path
  end

  def index
  end

  def show
    @organization = Organization.find_by_id(params[:id])
  end

  def activate
    organization = Organization.find(params[:organization_id])
    organization.activate
    UserMailer.delay(:queue => "organization_activation_mail").activation_mail(organization.cso_admins.first, organization.default_locale)
    flash[:notice] = t "status_changed", :organization_name => organization.name, :status => organization.status
    redirect_to organizations_path
  end

  def deactivate
    organization = Organization.find(params[:organization_id])
    organization.deactivate
    UserMailer.delay(:queue => "organization_deactivation_mail").deactivation_mail(organization.cso_admins.first, organization.default_locale, params[:deactivate_message])
    flash[:notice] = t "status_changed", :organization_name => organization.name, :status => organization.status
    redirect_to organizations_path
  end

  def destroy
    organization = Organization.find(params[:id])
    organization.soft_delete_self_and_associated
    reset_session
    flash[:notice] = I18n.t("organizations.destroy.organization_to_be_deleted")
    redirect_to root_path
  end
end

app/views/organizations/edit.html.erb
<header>
  <h2><%= t(".edit_organization", :organization_name => @organization.name) %></h2>
</header>

<%= semantic_form_for @organization do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
    <% if @organization.logo.present? %>
      <%= link_to image_tag(@organization.logo_url, :class => "organization-edit-logo-image"), @organization.logo_url %>
    <% end %>
    <%= f.input :logo %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :label => t(".update_organization_button_label") %>
  <% end %>
<% end %>

app/views/organizations/index.html.erb
<div id="admin">
  <% unless @organizations.empty? %>
  <header>
    <h2><%= t ".list_of_organizations" %></h2>
  </header>

  <div>
    <h2><%= t ".active" %></h2>
    <table>
      <% @organizations.select{ |org| org.status == Organization::Status::ACTIVE}.each do |organization|%>
      <tr>
        <td><%= organization.name %></td>
        <td>
          (<%= I18n.name_for_locale(organization.default_locale.to_sym) %>)</td>
        <td>
          <%= form_tag organization_deactivate_path(organization.id), :method => :put do %>
            <%= hidden_field_tag 'deactivate_message' %>
            <%= hidden_field_tag t(".deactivate")%>
          <% end %>

          <%= link_to t('.deactivate'), '#', :class =>'deactivate' if can? :deactivate, Organization %>
        </td>
        <td>
          <%= link_to t('.create_a_user'), new_organization_user_path(organization.id) if can? :manage, User %>
        </td>
        <td>
          <%= link_to t('.view_organization'), organization_path(organization.id) %>
        </td>
      </tr>
      <% end %></table>

    <h2><%= t ".inactive" %></h2>
    <table>
      <% @organizations.select{ |org| org.status == Organization::Status::INACTIVE}.each do |organization|%>
      <tr>
        <td><%= organization.name %></td>
        <td><%= button_to t('.activate'), organization_activate_path(organization.id), :method =>
        :put, :confirm => t(:confirm) if can? :manage, organization %></td>
      </tr>

      <% end %></table>
    </div>
  <% else %>
    <p><%= t(".no_organizations") if @organizations.empty? %></p>
  <% end %>
</div>

<script type="text/javascript">
  $(function(){
    $(".deactivate").click(function(e){
      var deactivate_message = <%= raw("prompt(\"") + t(".deactivate_prompt_message") + raw("\");")%>
      if(deactivate_message != null) {
        $("#deactivate_message").val(deactivate_message);
        $(e.target).prev('form').submit();
      }
    });
  });
</script>

app/views/organizations/new.html.erb
<div id="register">
  <header>
    <h2><%= t ".register_organization" %></h2>
  </header>

  <%= semantic_form_for @organization, :html => {:multipart => true} do |f| %>
    <%= f.inputs :name => t(".organization_info") do %>
      <%= f.input :name, :label => Organization.human_attribute_name(:name) %>
      <%= f.input :org_type, :label => Organization.human_attribute_name(:org_type),
        :as => :select, :collection => Organization.types %>
      <%= f.label "Upload Logo" %>
      <%= f.file_field :logo, :accept => "image/*" %>
    <% end %>


    <%= f.semantic_fields_for :users, @user do |user| %>
      <%= user.inputs :name => t(".user_info") do %>
        <%= user.input :name %>
        <%= user.input :email %>
        <%= user.input :password, :required => true %>
        <%= user.input :password_confirmation, :as => :password, :required => true %>
      <% end %>
    <% end %>

    <fieldset>
      <legend><%= t(".legal_heading") %></legend>
      <div class="organization-legal-item mandatory">
        <%= check_box_tag 'terms_of_service', nil, false, :class => 'organization-legal-item-checkbox' %>
        <%= label_tag 'terms_of_service', @organization.label_for_terms_of_service, :class => 'organization-legal-item-label' %>
      </div>

      <div class="organization-legal-item mandatory">
        <%= check_box_tag 'privacy_policy', nil, false, :class => 'organization-legal-item-checkbox' %>
        <%= label_tag 'privacy_policy', @organization.label_for_privacy_policy, :class => 'organization-legal-item-label' %>
      </div>

      <div class="organization-legal-item">
        <%= f.check_box :allow_sharing, :class => 'organization-legal-item-checkbox' %>
        <%= f.label :allow_sharing, t(".sharing_agreement"), :class => 'organization-legal-item-label' %>
      </div>
    </fieldset>

    <%= f.actions do %>
      <% f.action :submit, :label => t("register"), :as => :button, :button_html => { :disabled => true, :class => "organization-register-button" } %>
    <% end %>
  <% end %>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    new UserOwner.Registration($("#register"));
  });
</script>

app/views/organizations/show.html.erb
<header>
  <h2><%= @organization.name %></h2>
</header>
<div>
  <div>
    <h2>Status - <%= @organization.status %></h2>
    <h2>Type - <%= @organization.org_type %></h2>
    <h2>Default Locale - <%= I18n.name_for_locale(@organization.default_locale.to_sym) %></h2>
  </div>
</div>
<%= render "users/users_list", :users => @organization.users %>